Rails blog - Add views
ReshyResh/Rails-blog-app pull request #5
Opened 2021-12-06 20:31 UTC by ReshyResh

# Project requirements
  - Implement the views shown in the [Diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)

# Features
  - Setup partials for for improved performance and DRY code.
  - Used getters for the view, no data manipulation is being executed.

# Details
### I set up some data in the database to display in the view, as shown in the picture below.

![](https://i.imgur.com/hX8jRfG.png)

### Which results in the following views in the browser:

![](https://i.imgur.com/V4TSsex.png)

2021-12-06 22:10 UTC, rukundoeric requested changes
Hi @ReshyResh, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯

## Required Changes ♻️
  - [x] Before implementing the changes, I would like to recommend you go back and go through the Active Record lesson.
  - [x] And try to make sure that controllers aren't empty(try to follow MVC pattern) because most of the mistakes you made are based on that.
  - [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-06 22:10 UTC, rukundoeric commented on app/models/user.rb
>  end
- [ ] <b>REQUIRED:</b> You don't have to create a function just to get the number of posts. This would do the trick.

```ruby
@user.posts.size
```

2021-12-06 22:10 UTC, rukundoeric commented on app/views/layouts/partials/_userpostdetails.erb
> +<% post = Post.find_by(id: params["id"]) %>
- [ ] <b>REQUIRED:</b> You are not allowed to perform logic in the view. Remember, you can use post controller here by `show` function.

2021-12-06 22:10 UTC, rukundoeric commented on app/views/layouts/partials/_userposts.erb
> +<% user_posts = user.show_posts(params["user_id"]) %>
- [ ] <b>REQUIRED:</b> Also here, please use controller to handle this. you are not allowed to perform logic in the viewa. Kindly do that.

2021-12-07 08:54 UTC, ReshyResh commented on app/models/post.rb
> +  end
Done ✔

2021-12-07 08:55 UTC, ReshyResh commented on app/models/post.rb
>  end
Done ✔

2021-12-07 08:56 UTC, ReshyResh commented on app/models/user.rb
> +  end
### I implemented the suggested change, but I kept the function as it was a requirement of the previous milestone.
![](https://i.imgur.com/JjH0csc.png)

2021-12-07 09:08 UTC, ReshyResh commented on app/models/application_record.rb
>    end
Done ✔

2021-12-07 09:08 UTC, ReshyResh commented on app/models/comment.rb
> +  end
Done ✔

2021-12-07 09:09 UTC, ReshyResh commented on app/models/user.rb
>  end
Done ✔

2021-12-07 09:09 UTC, ReshyResh commented on app/views/layouts/partials/_userpostdetails.erb
> +<% post = Post.find_by(id: params["id"]) %>
Done ✔

2021-12-07 09:09 UTC, ReshyResh commented on app/views/layouts/partials/_userposts.erb
> +<% user_posts = user.show_posts(params["user_id"]) %>
Done ✔

2021-12-07 09:22 UTC, ReshyResh commented on app/models/comment.rb
>    end
### Since it is manipulating DB data, I think it should stay in the model, as requested in the previous milestone.

![](https://i.imgur.com/TMa2tZF.png)

2021-12-07 09:39 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Robert, 

Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂

<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 10:05 UTC, rloterh commented on app/models/post.rb
> +  end
This issue is well resolved! ✔️

2021-12-07 10:06 UTC, rloterh commented on app/models/post.rb
>  end
This issue is well resolved! ✔️

2021-12-07 10:06 UTC, rloterh commented on app/models/application_record.rb
>    end
This issue is well resolved! ✔️

2021-12-07 10:07 UTC, rloterh commented on app/models/comment.rb
> +  end
This issue is well resolved! ✔️

2021-12-07 10:07 UTC, rloterh commented on app/models/user.rb
>  end
This issue is well resolved! ✔️

2021-12-07 10:07 UTC, rloterh commented on app/views/layouts/partials/_userpostdetails.erb
> +<% post = Post.find_by(id: params["id"]) %>
This issue is well resolved! ✔️

2021-12-07 10:08 UTC, rloterh commented on app/views/layouts/partials/_userposts.erb
> +<% user_posts = user.show_posts(params["user_id"]) %>
This issue is well resolved! ✔️

2021-12-07 10:36 UTC, merged